### ISSUE TITLE
Assertion Failed : (hashPrevBlock == view.GetBestBlock() error

### ISSUE THREAD

**Issue by dogecash** [dogecash/dogecash#2]
Reported By E182#2407 on discord 

Possible Fixes:
PIVX PR : https://github.com/PIVX-Project/PIVX/pull/146/
Bitcoin PR : https://github.com/bitcoin/bitcoin/pull/7259

**Comment by dogecash** [comment]
another bug fix from bitcoin git 
https://github.com/bitcoin/bitcoin/pull/2781/

**Comment by akshaynexus** [comment]
Fix from PIVX is in code,closing issue
