### ISSUE TITLE
wallet: blockchain corrupted

### ISSUE THREAD

**Issue by jtomtan** [dogecash/dogecash#25]
When start the dogecash wallet (for Mac), it says blockchain corrupted and asked for reloading the whole blockchain.

**Comment by Liquid369** [comment]
We are have a fix implemented for next release.
The issue is due to the fork we had implemented in the last version, wallet.dat needs to be re-written by new client due to minimum protocol enforcement.
It will be fixed in the upcoming wallet release :)

**Comment by jtomtan** [comment]
> We are have a fix implemented for next release.
> The issue is due to the fork we had implemented in the last version, wallet.dat needs to be re-written by new client due to minimum protocol enforcement.
> It will be fixed in the upcoming wallet release :)

So the new client will update the wallet.dat automatically? Will copy old wallet.dat into new client work?

**Comment by akshaynexus** [comment]
we are looking in to the error,will close this issue once we have tested the fix and it works

**Comment by akshaynexus** [comment]
we have fixed this issue,closing issue.

**Comment by jtomtan** [comment]
Windows version crashed without any info.

**Comment by akshaynexus** [comment]
You need to send debug log, otherwise no idea on what's causing the issue

**Comment by akshaynexus** [comment]
Try reindexing or rescanning.Also make sure that you are on the right chain by cross checking with the explorer block count
