### ISSUE TITLE
Delete Makefile and add it to .gitignore

### ISSUE THREAD

**Issue by ParksProjets** [dogecash/dogecash#4]
The `Makefile` provided doesn't work because it uses absolute paths (that change from one computer to another). As we can generate this `Makefile` from `Makefile.am`, there is no reason to keep it in the **git** (like there is no reason to keep `.o` object files).

Please untack the `Makefile` from **git** and add it to `.gitignore` (because it's annoying when you have an automatic source builder).

**Comment by akshaynexus** [comment]
fixed
